name: JS Library

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update package.json version
        run: |
          NEW_VERSION=${{ inputs.version }}
          sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json

  publish:
    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read
      packages: write
    concurrency:
      group: npm-${{ github.repository }}
    runs-on: ubuntu-latest
    environment: npm
    needs: [build]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update package.json version
        run: |
          NEW_VERSION=${{ inputs.version }}
          sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json
