name: N8N

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update package.json version
        run: |
          NEW_VERSION=${{ inputs.version }}
          sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json

      - name: PNPM Install
        run: pnpm i
  
      - name: Build for publish
        run: pnpm run buildForPublish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read
      packages: write
    concurrency:
      group: npm-${{ github.repository }}
    runs-on: ubuntu-latest
    environment: npm
    needs: [build]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .

      - name: Publish to npm
        run: |
          ls -alh
